export const category = [
  { id: 1, name: 'cat1' },
  { id: 2, name: 'cat1' },
  { id: 3, name: 'cat1' },
  { id: 4, name: 'cat1' },
  { id: 5, name: 'cat1' },
  { id: 6, name: 'cat1' },
  { id: 7, name: 'cat1' },
];
export const item = [
  { id: 1, categoryId: 1, info: 'ddd1' },
  { id: 2, categoryId: 1, info: 'ervf' },
  { id: 3, categoryId: 2, info: 'fwesd' },
  { id: 4, categoryId: 3, info: 'data1' },
  { id: 5, categoryId: 1, info: 'data2' },
  { id: 6, categoryId: 1, info: 'data3' },
  { id: 7, categoryId: 1, info: 'data4' },
  { id: 8, categoryId: 1, info: 'data5' },
  { id: 9, categoryId: 1, info: 'data6' },
  { id: 10, categoryId: 1, info: 'data7' },
  { id: 11, categoryId: 1, info: 'data8' },
  { id: 12, categoryId: 1, info: 'data9' },
  { id: 13, categoryId: 1, info: 'data10' },
  { id: 14, categoryId: 1, info: 'data11' },
  { id: 15, categoryId: 1, info: 'data12' },
];
